# Generated by Django 4.1.2 on 2024-06-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('baseprice', models.IntegerField()),
                ('term', models.IntegerField()),
                ('income', models.FloatField(max_length=20)),
                ('earning', models.FloatField(max_length=20)),
                ('totalrevenue', models.FloatField(default=0, max_length=20)),
                ('totalyield', models.FloatField(max_length=20)),
                ('description', models.TextField()),
                ('purchaselimit', models.IntegerField()),
                ('desc1', models.CharField(blank=True, max_length=100, null=True)),
                ('desc2', models.CharField(blank=True, max_length=100, null=True)),
                ('desc3', models.CharField(blank=True, max_length=100, null=True)),
                ('desc4', models.CharField(blank=True, max_length=100, null=True)),
                ('desc5', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.CharField(default='In Stock', max_length=20)),
                ('pic1', models.ImageField(blank=True, default='noimagep.jpg', null=True, upload_to='images')),
                ('pic2', models.ImageField(blank=True, default='noimagep.jpg', null=True, upload_to='images')),
                ('pic3', models.ImageField(blank=True, default='noimagep.jpg', null=True, upload_to='images')),
            ],
        ),
    ]
