# Generated by Django 4.1.2 on 2024-06-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_bank_withdrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawn',
            name='bank',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='withdrawn',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
