# Generated by Django 4.1.2 on 2024-06-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_withdrawn_bank_alter_withdrawn_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='account',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyer',
            name='bank',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='buyer',
            name='ifsc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='buyer',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='buyer',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Withdrawn',
        ),
    ]
