# Generated by Django 4.1.2 on 2024-06-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_buyer_account_buyer_bank_buyer_ifsc_buyer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('account', models.IntegerField(default=0)),
                ('ifsc', models.CharField(default='', max_length=200)),
                ('bank', models.CharField(default='', max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
            ],
        ),
    ]
