# Generated by Django 4.1.2 on 2024-06-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_withdrawn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawn',
            old_name='Buyer',
            new_name='buyer',
        ),
    ]
