# Generated by Django 4.1.2 on 2024-06-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_recharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='dailyincome',
            field=models.IntegerField(default=0),
        ),
    ]
