# Generated by Django 4.1.2 on 2024-06-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_buyer_dailyincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buyer',
            name='product',
            field=models.IntegerField(default=0),
        ),
    ]
