# Generated by Django 4.1.2 on 2024-06-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_buyer_balance_buyer_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='rech',
            field=models.IntegerField(default=0),
        ),
    ]
