# Generated by Django 4.1.2 on 2024-06-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawn',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Done')], default=1),
        ),
    ]
