# Generated by Django 4.1.2 on 2024-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_withdrawn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawn',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
