# Generated by Django 4.1.2 on 2024-06-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_buyer_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
            ],
        ),
    ]
