# Generated by Django 4.1.2 on 2024-07-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='last_clicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
